### ISSUE TITLE
First order logic and types

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/hol-guidebook#3]
I may be pedantic, but I feel to know first order logic does not know about type, while some less known variants of it do. If I'm not wrong, may be in the FOL chapter, a note could be added to explicitly say HOL4 adds mandatory typing to its interpretation of FOL.

**Comment by mn200** [comment]
It might be better to simply rename that section “Quantifiers”.

**Comment by Hibou57** [comment]
So that's my bad. When @xrchz asked me what I believe should be presented in this document, I suggested to introduce FOL before HOL as it's more widely known than HOL.

**Comment by mn200** [comment]
Fair enough.  Certainly, I think it would be perfectly reasonable to say something like “HOL is like a combination of typed FOL (or many-sorted FOL) and functional programming”.

**Comment by Hibou57** [comment]
I have an another idea based on my experience as a novice. Basically (I'm talking as a novice), this explanation which is indeed the one always given, while true, does not say enough. More needs to be said to help, while not too much to not be intimidating. I will propose a wording in a few days.

**Comment by mn200** [comment]
That would be excellent!
